;title='Fan Control'
;creator='Kefir Team'
;version='1.0'
;color='green'

[Header]
;mode=table
;background=false
;header_indent=true
;gap=17
'Fan Settings' = ''

[Quiet Mode (minimal noise)]
;mini=true
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_console_on_fwdbg 'str!"[[-1000000, 36000, -255, 0], [36000, 40000, 0, 30], [40000, 47000, 30, 65], [47000, 50000, 65, 90], [50000, 54000, 90, 125], [54000, 1000000, 125, 180]]"'
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_handheld_on_fwdbg 'str!"[[-1000000, 33000, -255, 0], [33000, 36000, 0, 10], [36000, 43000, 10, 35], [43000, 47000, 35, 60], [47000, 50000, 60, 80], [50000, 1000000, 80, 120]]"'
set-ini-val './Custom/config.ini' Preset name 'Quiet Mode'
notify-now 'Quiet mode enabled'

[Balanced (cooling + quiet)]
;mini=true
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_console_on_fwdbg 'str!"[[-1000000, 36000, -255, 0], [36000, 40000, 0, 30], [40000, 47000, 30, 65], [47000, 50000, 65, 90], [50000, 54000, 90, 125], [54000, 1000000, 125, 180]]"'
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_handheld_on_fwdbg 'str!"[[-1000000, 33000, -255, 0], [33000, 36000, 0, 30], [36000, 43000, 30, 65], [43000, 47000, 65, 90], [47000, 50000, 90, 125], [50000, 1000000, 125, 180]]"'
set-ini-val './Custom/config.ini' Preset name 'Balanced'
notify-now 'Balanced mode enabled'

[Max Cooling (loud!)]
;mini=true
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_console_on_fwdbg 'str!"[[-1000000, 36000, -255, 25], [36000, 40000, 25, 40], [40000, 47000, 40, 75], [47000, 50000, 75, 100], [50000, 54000, 100, 135], [54000, 1000000, 135, 210]]"'
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_handheld_on_fwdbg 'str!"[[-1000000, 33000, -255, 25], [33000, 36000, 25, 40], [36000, 43000, 40, 75], [43000, 47000, 75, 100], [47000, 50000, 100, 135], [50000, 1000000, 135, 210]]"'
set-ini-val './Custom/config.ini' Preset name 'Max Cooling'
notify-now 'Max cooling enabled (loud!)'

[Gap]
;mode=table
;background=false
;gap=20

[*Custom Fan Curves]
;mode=forwarder
package_source './Custom/package.ini'

[Gap]
;mode=table
;background=false
;gap=20

[Reset to Stock]
;hold=true
remove-ini-key /atmosphere/config/system_settings.ini tc tskin_rate_table_console_on_fwdbg
remove-ini-key /atmosphere/config/system_settings.ini tc tskin_rate_table_handheld_on_fwdbg
notify-now 'Fan curves reset to stock'
