;title='Settings'
;creator='Kefir Team'
;version='1.0'
;color='green'

[Overclock status]
;hold=true
;mode=toggle
toggle_state file_exists /atmosphere/kips/kefir.kip
on:
try:
notify-now 'Enabling Overclock...'
copy /config/oc/ /
move /config/oc_bkp/config/sys-clk/config.ini /config/sys-clk/config.ini
reboot
off:
try:
notify-now 'Disabling Overclock...'
delete /atmosphere/contents/00FF0000636C6BFF/
delete /atmosphere/kips/kefir.kip
delete /bootloader/loader.kip
delete /switch/.overlays/sys-clk-overlay.ovl
move /config/sys-clk/config.ini /config/oc_bkp/config/sys-clk/config.ini
reboot

[40MB Memory]
;hold=true
;mode=toggle
; Перевіряємо значення force_40mb_applet у секції atmosphere
toggle_state ini_val /atmosphere/config/system_settings.ini 'atmosphere' force_40mb_applet u8!0x1
on:
try:
notify-now 'Enabling 40MB memory patch...'
set-ini-val /atmosphere/config/system_settings.ini 'atmosphere' force_40mb_applet u8!0x1
reboot
off:
try:
notify-now 'Disabling 40MB memory patch...'
set-ini-val /atmosphere/config/system_settings.ini 'atmosphere' force_40mb_applet u8!0x0
reboot

; [*Fan Control]
; ;mode=forwarder
; package_source './Fan Control/package.ini'

[*Advanced]

[Redirect Emunand saves to SD (experemental)]
;hold=true
;mode=toggle
; Перевіряємо значення fsmitm_redirect_saves_to_sd у секції atmosphere
toggle_visibility ini_val /emummc/emummc.ini 'emummc' enabled 1
toggle_state ini_val /atmosphere/config/system_settings.ini atmosphere fsmitm_redirect_saves_to_sd u8!0x1
delete /config/redirect.bin
on:
try:
notify-now 'Enabling Saves Redirect...'
set-ini-val /atmosphere/config/system_settings.ini 'atmosphere' fsmitm_redirect_saves_to_sd u8!0x1
reboot
off:
try:
notify-now 'Disabling Saves Redirect...'
set-ini-val /atmosphere/config/system_settings.ini 'atmosphere' fsmitm_redirect_saves_to_sd u8!0x0
delete /config/redirect.bin
reboot

[8GB DRAM status]
;mode=toggle
;hold=true
;hold_seconds=3
;warning_on=Only for consoles with physically\nsoldered 8GB RAM, others will\nnot work - error.\n\nTo disable:\nhekate>payloads>TegraExplorer>\nRemove_8GB-RAM_config.te
toggle_state file_exists /tegraexplorer/scripts/Remove_8GB-RAM_config.te
on:
try:
notify-now 'Enabling 8GB DRAM Mode...'
copy '/config/8gb/install.te' '/startup.te'
reboot '/bootloader/payloads/TegraExplorer.bin'
off:
try:
notify-now 'Disabling 8GB DRAM Mode...'
copy '/tegraexplorer/scripts/Remove_8GB-RAM_config.te' '/startup.te'
reboot '/bootloader/payloads/TegraExplorer.bin'