;title='Kefir Menu'
;creator='Kefir Team'
;version='1.0'
;color='green'

[Settings]
;mode=forwarder
package_source './Settings/config.ini'

[Software]
;mode=forwarder
package_source './Software/config.ini'

[Theme]
;mode=forwarder
package_source './Theme/config.ini'

[Translate Interface]
;mode=forwarder
package_source './Translate Interface/config.ini'

[Semi-Stock Mode]
;mode=toggle
on:
try:
notify-now 'Enabling Semi-Stock...'
set-ini-val /emummc/emummc.ini 'emummc' enabled 0
set-ini-val /exosphere.ini 'exosphere' blank_prodinfo_sysmmc 0
set-ini-val /bootloader/hekate_ipl.ini 'config' autoboot_list 0
move /atmosphere/contents/0100000000001000/romfs/lyt/ /config/ultrahand/romfs/lyt/
reboot
off:
try:
notify-now 'Returning to Kefir...'
set-ini-val /emummc/emummc.ini 'emummc' enabled 1
set-ini-val /exosphere.ini 'exosphere' blank_prodinfo_sysmmc 1
set-ini-val /bootloader/hekate_ipl.ini 'config' autoboot_list 1
move /config/ultrahand/romfs/lyt/ /atmosphere/contents/0100000000001000/romfs/lyt/
delete /config/ultrahand/romfs
reboot

[Shutdown]
;hold=true
try:
notify-now 'Shutting down...'
shutdown

[Reboot]
;hold=true
try:
notify-now 'Rebooting...'
reboot
