;title='Translate Interface'
;creator='Kefir Team'
;version='1.0'
;color='green'

[Info]
;mode=table
;spacing=1
;gap=15
;alignment=left
'Return back and come in again after downloading' = ''
'the translation packages.' = ''

[Gap]
;mode=table
;background=false
;gap=20

[Download language packs]
try:
notify-now 'Downloading language packs...'
download https://github.com/rashevskyv/switch-translations-mirrors/raw/main/lang_packs_ultra.zip '/config/sphaira/downloads/lang_packs.zip'
move '/config/sphaira/packages/Translate Interface/package.ini' '/config/sphaira/packages/translate_interface.package.ini.bkp'
delete '/config/sphaira/packages/Translate Interface/'
mkdir '/config/sphaira/packages/Translate Interface/'
copy '/config/sphaira/packages/translate_interface.package.ini.bkp' '/config/sphaira/packages/Translate Interface/package.ini.bkp'
unzip '/config/sphaira/downloads/lang_packs.zip' '/config/sphaira/packages/Translate Interface/'
delete '/config/sphaira/downloads/lang_packs.zip'

[Remove installed translation]
;hold=true
try:
notify-now 'Removing translations...'
delete '/atmosphere/contents/010000000000080B/'
delete '/atmosphere/contents/010000000000080C/'
delete '/atmosphere/contents/010000000000100D/'
delete '/atmosphere/contents/0100000000000803/'
delete '/atmosphere/contents/0100000000000811/'
delete '/atmosphere/contents/0100000000001000/romfs/message/'
delete '/atmosphere/contents/0100000000001001/'
delete '/atmosphere/contents/0100000000001002/'
delete '/atmosphere/contents/0100000000001003/'
delete '/atmosphere/contents/0100000000001004/'
delete '/atmosphere/contents/0100000000001005/'
delete '/atmosphere/contents/0100000000001006/'
delete '/atmosphere/contents/0100000000001007/'
delete '/atmosphere/contents/0100000000001008/'
delete '/atmosphere/contents/0100000000001009/'
delete '/atmosphere/contents/0100000000001012/'
delete '/atmosphere/contents/0100000000001013/'
delete '/atmosphere/contents/0100000000001015/'
reboot
