;title='DBI Installer'
;creator='Kefir Team'
;version='1.0'
;color='green'



[*DBI Translations]
;mode=forwarder
package_source './Fan Translations/package.ini'

[Russian latest]
try:
notify-now 'Downloading Russian DBI...'
download https://github.com/rashevskyv/DBI/releases/latest/download/DBI.nro /switch/DBI/DBI_new.nro
move /switch/DBI/DBI_new.nro /switch/DBI/DBI.nro

[Reset config]
;hold=true
try:
notify-now 'Resetting DBI Config...'
download https://github.com/rashevskyv/DBI/releases/latest/download/dbi.config /switch/DBI/dbi.config_new
move /switch/DBI/dbi.config_new /switch/DBI/dbi.config
