;title='Themes'
;creator='Kefir Team'
;version='1.0'
;color='green'

; Download theme
[Mario BG Dark]
try:
notify-now 'Downloading Mario BG Dark...'
download https://github.com/rashevskyv/mario_bg_theme/releases/latest/download/Mario.BG.Modern.zip '/config/ultrahand/downloads/theme.zip'
unzip '/config/ultrahand/downloads/theme.zip' '/themes/'
delete '/config/ultrahand/downloads/theme.zip'

[Switch 2 Theme by alexwak]
try:
notify-now 'Downloading Switch 2 Theme...'
download https://github.com/alexwak/Switch-2-Switch-Theme/releases/latest/download/Switch-2-Switch-Banned.zip '/config/ultrahand/downloads/theme.zip'
unzip '/config/ultrahand/downloads/theme.zip' '/themes/'
delete '/config/ultrahand/downloads/theme.zip'
