;title='Custom Fan Curves'
;creator='Kefir Team'
;version='1.0'
;color='green'

[Info]
;mode=table
;spacing=1
;gap=15
;alignment=left
ini_file './config.ini'
'Current Preset' = '{ini_file(Preset,name)}'
' ' = ' '
'Adjust fan speed (0-255) for each temperature.' = ''
'Move sliders then press Apply' = ''
' ' = ' '
'Tip: Enable Status Monitor overlay' = ''
'to see real-time temperature' = ''

[Gap]
;mode=table
;background=false
;gap=20

[@Handheld Mode]

[33°C Fan Speed]
;mode=trackbar
;min_value=0
;max_value=255
;units=%
ini_file './config.ini'
set-ini-val './config.ini' '33°C?H' value {value}
set-ini-val './config.ini' Preset name 'Custom'

[43°C Fan Speed]
;mode=trackbar
;min_value=0
;max_value=255
;units=%
ini_file './config.ini'
set-ini-val './config.ini' '43°C?H' value {value}
set-ini-val './config.ini' Preset name 'Custom'

[50°C Fan Speed]
;mode=trackbar
;min_value=0
;max_value=255
;units=%
ini_file './config.ini'
set-ini-val './config.ini' '50°C?H' value {value}
set-ini-val './config.ini' Preset name 'Custom'

[Gap]
;mode=table
;background=false
;gap=20

[@Docked Mode]

[40°C Fan Speed]
;mode=trackbar
;min_value=0
;max_value=255
;units=%
ini_file './config.ini'
set-ini-val './config.ini' '40°C?D' value {value}
set-ini-val './config.ini' Preset name 'Custom'

[47°C Fan Speed]
;mode=trackbar
;min_value=0
;max_value=255
;units=%
ini_file './config.ini'
set-ini-val './config.ini' '47°C?D' value {value}
set-ini-val './config.ini' Preset name 'Custom'

[54°C Fan Speed]
;mode=trackbar
;min_value=0
;max_value=255
;units=%
ini_file './config.ini'
set-ini-val './config.ini' '54°C?D' value {value}
set-ini-val './config.ini' Preset name 'Custom'

[Gap]
;mode=table
;background=false
;gap=20

[Apply Changes]
;mini=true
ini_file './config.ini'
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_handheld_on_fwdbg 'str!"[[-1000000, 33000, -255, 0], [33000, 36000, 0, {ini_file(33°C?H,value)}], [36000, 43000, {ini_file(33°C?H,value)}, {ini_file(43°C?H,value)}], [43000, 47000, {ini_file(43°C?H,value)}, 90], [47000, 50000, 90, {ini_file(50°C?H,value)}], [50000, 1000000, {ini_file(50°C?H,value)}, 255]]"'
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_console_on_fwdbg 'str!"[[-1000000, 36000, -255, 0], [36000, 40000, 0, {ini_file(40°C?D,value)}], [40000, 47000, {ini_file(40°C?D,value)}, {ini_file(47°C?D,value)}], [47000, 50000, {ini_file(47°C?D,value)}, 90], [50000, 54000, 90, {ini_file(54°C?D,value)}], [54000, 1000000, {ini_file(54°C?D,value)}, 255]]"'
notify-now 'Custom fan curves applied'
