;title='Software'
;creator='Kefir Team'
;version='1.0'
;color='green'

[*DBI]
;mode=forwarder
package_source './DBI/package.ini'


[*Mod Utilites]

[Info]
;mode=table
;spacing=1
;start_gap=15
;alignment=left
'Ukrainian mods' = ''

[UAModDownloader]
try:
notify-now 'Downloading UAModDownloader...'
download https://github.com/pro100luk/UAModDownloader/releases/latest/download/UAModDownloader.nro /switch/UAModDownloader/UAModDownloader_new.nro
move /switch/UAModDownloader/UAModDownloader_new.nro /switch/UAModDownloader/UAModDownloader.nro

[Gap]
;mode=table
;background=false
;gap=15

[Info]
;mode=table
;spacing=1
;start_gap=15
;alignment=left
'ECLIPS graphiс mods' = ''

[ModCD]
try:
notify-now 'Downloading ModCD...'
download https://github.com/kawaii-flesh/ModCD/releases/latest/download/ModCD.nro /switch/ModCD/ModCD_new.nro
move /switch/ModCD/ModCD_new.nro /switch/ModCD/ModCD.nro

[Gap]
;mode=table
;background=false
;gap=15

[Info]
;mode=table
;spacing=1
;start_gap=15
;alignment=left
'Game mods from gamebanana' = ''

[SimpleModDownloader]
try:
notify-now 'Downloading SimpleModDownloader...'
download https://github.com/PoloNX/SimpleModDownloader/releases/latest/download/SimpleModDownloader.nro /switch/SimpleModDownloader/SimpleModDownloader_new.nro
move /switch/SimpleModDownloader/SimpleModDownloader_new.nro /switch/SimpleModDownloader/SimpleModDownloader.nro

[Gap]
;mode=table
;background=false
;gap=15